pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "527552777739"   // CHANGE THIS
        ECR_REPOSITORY = "527552777739.dkr.ecr.us-east-1.amazonaws.com/signlang"       // CHANGE THIS
        IMAGE_TAG = "latest"
    }

    stages {

        stage('CI') {
            steps {
                echo "Linting repository"
                echo "Running unit tests"
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    sh '''
                      aws ecr get-login-password --region $AWS_REGION \
                      | docker login --username AWS \
                      --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    '''
                }
            }
        }

        stage('Build Image') {
            steps {
                sh '''
                  docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
                  docker tag $ECR_REPOSITORY:$IMAGE_TAG \
                  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                  docker push \
                  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
                '''
            }
        }
    }

    post {
        always {
            sh 'docker system prune -f'
        }
    }
}
